section header removed
WPAFC/afch-rewrite pull request #155
Opened 2021-03-10 08:13 UTC by Adityachaturvedi2906

2021-03-10 08:53 UTC, enterprisey requested changes
Looks good - please make the indicated change.

2021-03-10 08:53 UTC, enterprisey commented on src/afch.js
> +	AFCH.consts.mockItUp = true;
Please remove this line from the change, as it was only needed for testing

2021-03-10 11:53 UTC, Adityachaturvedi2906 commented on src/afch.js
> +	AFCH.consts.mockItUp = true;
> 
> 
> Please remove this line from the change, as it was only needed for testing

ok, I removed this line

2021-03-12 08:30 UTC, enterprisey commented
Thanks for your work on this!

2021-03-12 08:30 UTC, merged

2021-03-16 14:08 UTC, Adityachaturvedi2906 commented
> Thanks for your work on this!

Its was my pleasure ☺